[package]
name = "mailcatcher-lib"
version = "0.1.0"
authors = ["Lolo_32 <lol.b@free.fr>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[[bin]]
name = "mailcatcher"
path = "src/main.rs"

[dependencies]
async-channel = "1.5.1"
broadcaster = "1.0.0"
encoding = "0.2.33"
env_logger = "0.8.2"
fnv = "1.0.7"
futures = "0.3.8"
lazy_static = "1.4.0"
log = "0.4.11"
miniz_oxide = "0.4.3"
quote = "1"
rust-embed = "5.7.0"
serde = "1.0.117"
#sled = "0.34"
syn = "1"
ulid = "0.4.1"

[dependencies.async-std]
version = "1.7.0"
#features = ["unstable"]

[dependencies.base64]
version = "0.13.0"
default-features = false

[dependencies.chrono]
version = "0.4.19"
default-features = false

[dependencies.regex]
version = "1.4.2"
default-features = false
# feature std needed by regex
features = ["std"]

[dependencies.tide]
version = "0.15.0"
default-features = false
features = ["h1-server"]