[package]
name = "mailcatcher"
version = "0.1.0"
authors = ["Lolo_32 <lol.b@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.7"
chrono = "0.4"
env_logger = "0.8"
#futures = "0.3"
log = "0.4"
#rustls = "0.18"
#sled = "0.34"
